BlogApp.WebUI/Controllers/RegisterController.cs
using BlogApp.BusinessLayer.Abstract;
using BlogApp.BusinessLayer.Utilities.ValidationRules.FluentValidation;
using BlogApp.EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogApp.WebUI.Controllers
{
    public class RegisterController : Controller
    {
        IAuthorService _authService;

        public RegisterController(IAuthorService authService)
        {
            _authService = authService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(Author author)
        {
            AuthorValidator authorValidator = new AuthorValidator();
            ValidationResult results = authorValidator.Validate(author);
            if (results.IsValid)
            {
                author.Status = true;
                author.About = "Deneme";
                _authService.Add(author);
                return RedirectToAction("Index", "Blogs");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
    }
}

BlogApp.WebUI/Views/Register/Index.cshtml
@model BlogApp.EntityLayer.Concrete.Author

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/UserLayout.cshtml";
}
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="~/lib/jquery/dist/jquery.js"></script>

<section class="main-content-w3layouts-agileits">
    <div class="container">
        <h3 class="tittle">Register Now</h3>
        <div class="inner-sec">
            <div class="login p-5 bg-light mx-auto mw-100">
                @using (Html.BeginForm("Index", "Register", FormMethod.Post))
                {
                    <div class="form-row">
                        <div class="col-md-6 mb-3">
                            <label for="validationCustom01">Full name</label>
                            @Html.TextBoxFor(w => w.Name, new { @class = "form-control" })
                            @Html.ValidationMessageFor(w => w.Name,"", new { @class = "text-danger" })
                            @*<input type="text" class="form-control" id="validationDefault01" name="Name" placeholder="" required="">*@
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="validationCustom02">Email</label>
                            @Html.TextBoxFor(w => w.Email, new { @class = "form-control" })
                            @Html.ValidationMessageFor(w => w.Email, "", new { @class = "text-danger" })
                            @*<input type="email" class="form-control" id="validationDefault02" name="Email" placeholder="" required="">*@
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="exampleInputPassword1 mb-2">Password</label>
                            @Html.TextBoxFor(w => w.Password, new { @class = "form-control" })
                            @Html.ValidationMessageFor(w => w.Password, "", new { @class = "text-danger" })
                            @*<input type="password" class="form-control" id="password1" name="Password" placeholder="" required="">*@
                        </div>
                        <div class="form-group col-md-6">
                            <label for="exampleInputPassword2 mb-2">Image Path</label>
                            @Html.TextBoxFor(w => w.Image, new { @class = "form-control" })
                            @Html.ValidationMessageFor(w => w.Image, "", new { @class = "text-danger" })
                            @*<input type="text" class="form-control" id="password2" name="Image" placeholder="" required="">*@
                        </div>

                    </div>
                    <button type="submit" class="btn btn-primary submit mb-4">Register</button>
                    <p>
                        <a href="#" id="conditionconfirmation">By clicking Signup, I agree to your terms</a>
                    </p>
                }
            </div>
        </div>
    </div>
    <script>
        $('conditionconfirmation').click(function () {
            swal("You confirmed all the conditions!!");
        });
    </script>
</section>